/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productoperations_ui;

import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import model.dao.Productinfo_DAO;
import model.dao.Productstock_DAO;
import model.to.Productinfo_TO;
import model.to.Productstock_TO;
import utility.Checks;

/**
 *
 * @author LAKSHAY DUTTA
 */
public class Add_to_stock extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_to_stock
     */
    private int o, productid, quantity;
    private float price, discount;
    private Date expirydate;
    private boolean allvalid;
    private String message;

    public Add_to_stock(int o) {
        initComponents();
        setSize(750, 400);
        this.o = o;
        switch (o) {
            case 1:
                jcb_sid.removeAllItems();
                jcb_sid.addItem("This field is autogenerated");
                jcb_sid.setEnabled(false);
                break;
            case 2:
                List<Productstock_TO> allstockids = new Productstock_DAO().getallrecord();
                if (allstockids != null && allstockids.size() > 0) {
                    for (Productstock_TO ps : allstockids) {
                        jcb_sid.addItem(ps);
                    }
                }
                break;
        }
        List<Productinfo_TO> allproductids = new Productinfo_DAO().getallrecords();
        jcb_pid.removeAllItems();
        jcb_pid.addItem("Select Product id");
        if (allproductids != null && allproductids.size() > 0) {
            for (Productinfo_TO pi : allproductids) {
                jcb_pid.addItem(pi);
            }
        }
        jcb_year.removeAllItems();
        jcb_month.removeAllItems();
        jcb_year.addItem("Year");
        jcb_month.addItem("Month");
        for (int y = 2018; y < 2150; y++) {
            jcb_year.addItem(y);

        }
        for (String m : Checks.month_names) {
            jcb_month.addItem(m);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcb_sid = new javax.swing.JComboBox();
        jcb_pid = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_q = new javax.swing.JTextField();
        tf_p = new javax.swing.JTextField();
        tf_d = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jcb_month = new javax.swing.JComboBox();
        jcb_year = new javax.swing.JComboBox();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Select stock ID :-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 412, 34);

        jcb_sid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_sid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcb_sid);
        jcb_sid.setBounds(440, 11, 221, 34);

        jcb_pid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_pid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcb_pid);
        jcb_pid.setBounds(440, 56, 221, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Select Product ID :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 56, 412, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Set Price");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 148, 381, 34);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Enter Quantity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 96, 381, 34);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Select Discount");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 249, 262, 34);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Select Expiry Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 195, 169, 43);

        tf_q.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tf_q.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_qKeyTyped(evt);
            }
        });
        getContentPane().add(tf_q);
        tf_q.setBounds(440, 96, 221, 34);

        tf_p.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tf_p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_pKeyTyped(evt);
            }
        });
        getContentPane().add(tf_p);
        tf_p.setBounds(440, 148, 221, 34);

        tf_d.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tf_d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_dKeyTyped(evt);
            }
        });
        getContentPane().add(tf_d);
        tf_d.setBounds(434, 249, 228, 34);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 301, 158, 41);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(545, 301, 117, 32);

        jcb_month.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcb_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcb_month);
        jcb_month.setBounds(576, 200, 80, 30);

        jcb_year.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcb_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcb_year);
        jcb_year.setBounds(486, 200, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    int month, year;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
///////////////
        allvalid = true;
        if (jcb_pid.getSelectedIndex() < 0 || Checks.isempty(tf_d.getText()) || Checks.isempty(tf_p.getText()) || Checks.isempty(tf_q.getText()) || jcb_year.getSelectedIndex() < 0 || jcb_month.getSelectedIndex() < 0) {
            message = "Please fill all fields properly";
            allvalid = false;
        }
        if (allvalid) {
            Productinfo_TO pi = (Productinfo_TO) jcb_pid.getSelectedItem();
            productid = pi.getProductid();
            quantity = Integer.parseInt(tf_q.getText().trim());
            price = Integer.parseInt(tf_p.getText().trim());
            discount = Integer.parseInt(tf_d.getText().trim());
            year = (int) jcb_year.getSelectedItem();
            String month_name = (String) jcb_month.getSelectedItem();
            month = Checks.month_number(month_name);
            Productstock_TO record = new Productstock_TO();
            record.setDiscount(discount);
            record.setPrice(price);
            record.setQuantity(quantity);
            record.setProductid(productid);
            String datevalue = year + "-" + month + "-" + 01;
            expirydate = Date.valueOf(datevalue);
            record.setExpirydate(expirydate);
            Productstock_DAO action = new Productstock_DAO();
            switch (o) {
                case 1:
                    if (action.insertrecord(record)) {
                        message = " record was added in System";
                    } else {
                        message = " Insertion failed :" + action.getErrormessage();
                        allvalid = false;
                    }
                    break;
                case 2:
                    if(jcb_pid.getSelectedIndex()<0)
                    {
                        message = " please fill all fields properly";
                        allvalid=false;
                        break;
                    }
                    Productstock_TO ps = (Productstock_TO) jcb_sid.getSelectedItem();
                    record.setProductid(ps.getProductid());
                    if (action.updaterecord(record)) {
                        message = " record was updated in System";
                    } else {
                        message = " updation failed :" + action.getErrormessage();
                        allvalid = false;
                    }
                    break;
            }
        }

        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_qKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_qKeyTyped
        if(!Checks.keytype_int(evt))
            evt.consume();
    }//GEN-LAST:event_tf_qKeyTyped

    private void tf_pKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pKeyTyped
        if(!Checks.keytype_float(evt))
            evt.consume();
    }//GEN-LAST:event_tf_pKeyTyped

    private void tf_dKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_dKeyTyped
        if(!Checks.keytype_float(evt))
            evt.consume();
    }//GEN-LAST:event_tf_dKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox jcb_month;
    private javax.swing.JComboBox jcb_pid;
    private javax.swing.JComboBox jcb_sid;
    private javax.swing.JComboBox jcb_year;
    private javax.swing.JTextField tf_d;
    private javax.swing.JTextField tf_p;
    private javax.swing.JTextField tf_q;
    // End of variables declaration//GEN-END:variables
}
