/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productoperations_ui;

import java.util.List;
import javax.swing.JOptionPane;
import model.dao.Brandinfo_DAO;
import model.dao.Productinfo_DAO;
import model.dao.Subcategoryinfo_DAO;
import model.to.Brandinfo_TO;
import model.to.Productinfo_TO;
import model.to.Subcategoryinfo_TO;
import utility.Checks;

/**
 *
 * @author LAKSHAY DUTTA
 */
public class Input_product_details extends javax.swing.JInternalFrame {

    /**
     * Creates new form Input_product_details
     */
    private int o, productid, subcategoryid, avaialablequantity;
    private float price;
    private String brandid, productname, message;
    private boolean allvalid;

    public Input_product_details(int o) {
        initComponents();
        setSize(580, 415);
        this.o = o;
        jcb_bid.removeAllItems();
        jcb_bid.addItem("please select a Brand ID");
        List<Brandinfo_TO> allbrandids = new Brandinfo_DAO().getallrecords();
        if (allbrandids != null && allbrandids.size() > 0) {
            for (Brandinfo_TO bi : allbrandids) {
                jcb_bid.addItem(bi);
            }
        }
        jcb_scid.removeAllItems();
        jcb_scid.addItem("please select Sub category id");
        List<Subcategoryinfo_TO> allsubcategoryids = new Subcategoryinfo_DAO().getallrecords();
        if (allsubcategoryids != null && allsubcategoryids.size() > 0) {
            for (Subcategoryinfo_TO sc : allsubcategoryids) {
                jcb_scid.addItem(sc);
            }
        }
        switch (o) {
            case 1:
                jcb_pid.removeAllItems();
                jcb_pid.addItem("This field is autogenerated");
                jcb_pid.setEnabled(false);
                break;
            case 2:
                jcb_pid.removeAllItems();
                jcb_pid.addItem("please select Product id");
                List<Productinfo_TO> allproductids = new Productinfo_DAO().getallrecords();
                if (allproductids != null && allproductids.size() > 0) {
                    for (Productinfo_TO po : allproductids) {
                        jcb_pid.addItem(po);
                    }
                }
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcb_pid = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tf_pn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcb_bid = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jcb_scid = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tf_p = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_aq = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Product ID :-");

        jcb_pid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_pid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Enter Product name :-");

        tf_pn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Select Brand ID");

        jcb_bid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_bid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Select Subcategory ID");

        jcb_scid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_scid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Enter Price");

        tf_p.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tf_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pActionPerformed(evt);
            }
        });
        tf_p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_pKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Set avaialable quantity");

        tf_aq.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tf_aq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_aqKeyTyped(evt);
            }
        });

        save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_pn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_bid, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_scid, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_p, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_aq, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jcb_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_bid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_scid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_p, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_aq, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        allvalid = true;
        productname = tf_pn.getText().trim();
        price = Float.parseFloat(tf_p.getText().trim());
        avaialablequantity = Integer.parseInt(tf_aq.getText().trim());
        if (Checks.isempty(productname) || Checks.isempty(tf_p.getText()) || Checks.isempty(tf_aq.getText())) {
            message = " please fill all values";
            allvalid = false;
        }
        if (jcb_bid.getSelectedIndex() > 0 || jcb_scid.getSelectedIndex() > 0) {
            Brandinfo_TO b = (Brandinfo_TO) jcb_bid.getSelectedItem();
            Subcategoryinfo_TO s = (Subcategoryinfo_TO) jcb_scid.getSelectedItem();
            brandid = b.getBrandid();
            subcategoryid = s.getSubcategoryid();
        } else {
            allvalid = false;
        }
        if (allvalid) {
            Productinfo_TO record = new Productinfo_TO();
            record.setProductname(productname);
            record.setBrandid(brandid);
            record.setSubcategoryid(subcategoryid);
            record.setPrice(price);
            record.setAvailablequantity(avaialablequantity);
            Productinfo_DAO action = new Productinfo_DAO();
            switch (o) {
                case 1:
                    if (action.insertrecord(record)) {
                        message = " product information was added in System";
                    } else {
                        message = "Insertion failure ::" + action.getErrormessage();
                    }
                    break;
                case 2:
                    if (jcb_pid.getSelectedIndex() > 0) {
                        Productinfo_TO p = (Productinfo_TO) jcb_pid.getSelectedItem();
                        record.setProductid(p.getProductid());
                    }else{
                        allvalid=false;
                        message = "fill all fields properly";
                        break;
                    }
                    if (action.updaterecord(record)) {
                        message = "product information was updated in System";
                    } else {
                        message = " Updation failure ::" + action.getErrormessage();
                    }
                    break;
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_saveActionPerformed

    private void tf_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pActionPerformed

    }//GEN-LAST:event_tf_pActionPerformed

    private void tf_pKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pKeyTyped
        if (!Checks.keytype_float(evt)) {
            evt.consume();
        }
    }//GEN-LAST:event_tf_pKeyTyped

    private void tf_aqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_aqKeyTyped
        if (!Checks.keytype_int(evt)) {
            evt.consume();
        }
    }//GEN-LAST:event_tf_aqKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox jcb_bid;
    private javax.swing.JComboBox jcb_pid;
    private javax.swing.JComboBox jcb_scid;
    private javax.swing.JButton save;
    private javax.swing.JTextField tf_aq;
    private javax.swing.JTextField tf_p;
    private javax.swing.JTextField tf_pn;
    // End of variables declaration//GEN-END:variables
}
