/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package partydetails_ui;

import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import model.dao.Partyinfo_DAO;
import model.to.Partyinfo_TO;
import utility.Checks;

/**
 *
 * @author LAKSHAY DUTTA
 */
public class Insert_party extends javax.swing.JInternalFrame {

    /**
     * Creates new form Insert_party
     */
    private int o;
    private static int year, month, date, partyid;
    private String partyname, contactno, adress, uname, message;
    private Date entrydate;
    private boolean allvalid;

    public Insert_party(int o, String username) {
        this.o = o;
        //System.out.println(username);
        uname = username;
        //System.out.println(uname);
        // lbl_uname.setText(uname);
        initComponents();
        setSize(700, 400);
        lbl_uname.setText(uname);
        switch (o) {
            case 1:
                jcb_pid.removeAllItems();
                jcb_pid.addItem("this field is autogenerated");
                jcb_pid.setEnabled(false);
                break;
            case 2:
                jcb_pid.removeAllItems();
                List<Partyinfo_TO> allpartynames = new Partyinfo_DAO().getallrecords(uname);
                if (allpartynames != null && allpartynames.size() > 0) {
                    for (Partyinfo_TO li : allpartynames) {
                        jcb_pid.addItem(li);
                    }
                }
                break;
        }
        /* jcb_un.removeAllItems();
         jcb_un.addItem("select a User");
         List<Logininfo_TO> allusers = new Logininfo_DAO().getallrecords();
         if (allusers != null && allusers.size() > 0) {
         for (Logininfo_TO li : allusers) {
         jcb_un.addItem(li);
         }
         }*/
        jcb_year.removeAllItems();
        jcb_month.removeAllItems();
        jcb_year.addItem("Year");
        jcb_month.addItem("Month");
        for (int y = 2018; y < 2150; y++) {
            jcb_year.addItem(y);

        }
        for (String m : Checks.month_names) {
            jcb_month.addItem(m);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_pn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_cn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcb_year = new javax.swing.JComboBox();
        jcb_month = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_ad = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        tf_pn1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_cn1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcb_year1 = new javax.swing.JComboBox();
        jcb_month1 = new javax.swing.JComboBox();
        jcb_date1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_ad1 = new javax.swing.JTextArea();
        jcb_un1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jcb_pid = new javax.swing.JComboBox();
        tf_date = new javax.swing.JTextField();
        lbl_uname = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Enter party name");

        tf_pn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Enter contact number");

        tf_cn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tf_cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_cnKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Enter Adress");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("select entry date");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Enter Username");

        jcb_year.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_yearItemStateChanged(evt);
            }
        });
        jcb_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_yearActionPerformed(evt);
            }
        });

        jcb_month.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_monthItemStateChanged(evt);
            }
        });
        jcb_month.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcb_monthFocusGained(evt);
            }
        });
        jcb_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_monthActionPerformed(evt);
            }
        });

        ta_ad.setColumns(20);
        ta_ad.setRows(5);
        jScrollPane1.setViewportView(ta_ad);

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jInternalFrame1.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Enter party name");
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 60, 311, 33);

        tf_pn1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jInternalFrame1.getContentPane().add(tf_pn1);
        tf_pn1.setBounds(360, 60, 212, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Enter contact number");
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 100, 311, 33);

        tf_cn1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jInternalFrame1.getContentPane().add(tf_cn1);
        tf_cn1.setBounds(360, 100, 212, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Enter Adress");
        jInternalFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 140, 311, 33);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("select entry date");
        jInternalFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 270, 220, 33);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Enter Username");
        jInternalFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 230, 311, 33);

        jcb_year1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_year1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_year1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_year1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jcb_year1);
        jcb_year1.setBounds(300, 270, 100, 40);

        jcb_month1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_month1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jInternalFrame1.getContentPane().add(jcb_month1);
        jcb_month1.setBounds(410, 270, 120, 40);

        jcb_date1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_date1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jInternalFrame1.getContentPane().add(jcb_date1);
        jcb_date1.setBounds(540, 270, 90, 40);

        ta_ad1.setColumns(20);
        ta_ad1.setRows(5);
        jScrollPane2.setViewportView(ta_ad1);

        jInternalFrame1.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(360, 140, 210, 80);

        jcb_un1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_un1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jInternalFrame1.getContentPane().add(jcb_un1);
        jcb_un1.setBounds(360, 230, 210, 30);

        jButton3.setText("SAVE");
        jInternalFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(50, 330, 140, 50);

        jButton4.setText("close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(540, 330, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Select party ID");

        jcb_pid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jcb_pid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_pidActionPerformed(evt);
            }
        });

        tf_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_dateKeyTyped(evt);
            }
        });

        lbl_uname.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(tf_cn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(350, 350, 350)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jcb_year, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jcb_month, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(tf_date, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(tf_pn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_uname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcb_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lbl_uname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_year, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_month, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_yearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcb_year1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_year1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_year1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        allvalid = true;

        partyname = tf_pn.getText().trim();
        contactno = tf_cn.getText().trim();
        adress = ta_ad.getText().trim();
        date = Integer.parseInt(tf_date.getText());
        if (Checks.isempty(partyname) || Checks.isempty(contactno) || Checks.isempty(adress)) {
            message = " please fill all boxes";
            allvalid = false;
        }
        if (jcb_year.getSelectedIndex() > 0) {
            year = (int) jcb_year.getSelectedItem();
            //System.out.println(year);
        } else {
            allvalid = false;
        }
        if (jcb_month.getSelectedIndex() > 0) {
            String month_name = (String) jcb_month.getSelectedItem();
            month = Checks.month_number(month_name);
            //System.out.println(month);
        }
        if (jcb_year.getSelectedIndex() < 0 || jcb_month.getSelectedIndex() < 0 || Checks.isempty(tf_date.getText())) {
            allvalid = false;
        }
        if(!Checks.date_check(date, month, year))
        {
            message = "incorrect date was input";
            allvalid=false;
        }
        /* if (jcb_un.getSelectedIndex() > 0) {
         Logininfo_TO li = (Logininfo_TO) jcb_un.getSelectedItem();
         uname = li.getUname();
         } else {
         allvalid = false;
         }
        if (allvalid == false) {
            message = "One or more fields are not filled";
        }*/
        if (allvalid) {
            Partyinfo_TO record = new Partyinfo_TO();
            String datevalue = year + "-" + month + "-" + date;
            entrydate = Date.valueOf(datevalue);
            record.setAdress(adress);
            record.setContactno(contactno);
            record.setPartyname(partyname);
            record.setUname(uname);
            record.setEntrydate(entrydate);
            Partyinfo_DAO action = new Partyinfo_DAO();
            switch (o) {
                case 1:
                    if (action.insertrecord(record)) {
                        message = " partyinfo was added in system";
                    } else {
                        message = "insertion failure" + action.getErrormessage();
                    }
                    break;
                case 2:
                    Partyinfo_TO pi = (Partyinfo_TO) jcb_pid.getSelectedItem();
                    partyid = pi.getPartyid();
                    record.setPartyid(partyid);
                    if (action.updaterecord(record)) {
                        message = " partyinfo was updated in System";
                    } else {
                        message = "updation failure" + action.getErrormessage();

                    }
                    break;
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcb_monthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_monthItemStateChanged
//////////////////
        //System.out.println("item state changes");

    }//GEN-LAST:event_jcb_monthItemStateChanged

    private void jcb_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_monthActionPerformed

    }//GEN-LAST:event_jcb_monthActionPerformed

    private void jcb_monthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcb_monthFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_monthFocusGained

    private void jcb_yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_yearItemStateChanged
        // System.out.println("year ISC");
    }//GEN-LAST:event_jcb_yearItemStateChanged

    private void tf_dateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_dateKeyTyped
        if (!Checks.keytype_int(evt)) {
            evt.consume();
        }
    }//GEN-LAST:event_tf_dateKeyTyped

    private void jcb_pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_pidActionPerformed

    private void tf_cnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cnKeyTyped
        if(!Checks.keytype_int(evt))
            evt.consume();
    }//GEN-LAST:event_tf_cnKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcb_date1;
    private javax.swing.JComboBox jcb_month;
    private javax.swing.JComboBox jcb_month1;
    private javax.swing.JComboBox jcb_pid;
    private javax.swing.JComboBox jcb_un1;
    private javax.swing.JComboBox jcb_year;
    private javax.swing.JComboBox jcb_year1;
    private javax.swing.JLabel lbl_uname;
    private javax.swing.JTextArea ta_ad;
    private javax.swing.JTextArea ta_ad1;
    private javax.swing.JTextField tf_cn;
    private javax.swing.JTextField tf_cn1;
    private javax.swing.JTextField tf_date;
    private javax.swing.JTextField tf_pn;
    private javax.swing.JTextField tf_pn1;
    // End of variables declaration//GEN-END:variables
}
