/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brandoperations_ui;

import java.util.List;
import javax.swing.JOptionPane;
import model.dao.Brandinfo_DAO;
import model.dao.Brandsubcategory_DAO;
import model.dao.Subcategoryinfo_DAO;
import model.to.Brandinfo_TO;
import model.to.Brandsubcategory_TO;
import model.to.Subcategoryinfo_TO;
import utility.Checks;

/**
 *
 * @author LAKSHAY DUTTA
 */
public class Input_brandsubcategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form ibs
     */
    private int o;
    public Input_brandsubcategory(int o) {
        initComponents();
        setSize(650, 360);
        setVisible(true);
        this.o=o;
        jcb_bid.removeAllItems();
        jcb_bid.addItem("Select Brand ID");
        List<Brandinfo_TO> allbrands =new Brandinfo_DAO().getallrecords();
        if(allbrands != null && allbrands.size()>0)
        {
            for(Brandinfo_TO bi : allbrands)
            {
                jcb_bid.addItem(bi);
            }
        }
        jcb_scid.removeAllItems();
        jcb_scid.addItem("Select Subcategory ID");
        List<Subcategoryinfo_TO> allsubcategoryids =new Subcategoryinfo_DAO().getallrecords();
        if(allbrands != null && allbrands.size()>0)
        {
            for(Subcategoryinfo_TO bi : allsubcategoryids)
            {
                jcb_scid.addItem(bi);
            }
        }
        jcb_bsid.removeAllItems();
        switch(o)
        {
            case 1:
                jcb_bsid.addItem("this field is autogenerated");
                jcb_bsid.setEnabled(false);
                break;
            case 2:
                List<Brandsubcategory_TO> allbrandsubcategories = new Brandsubcategory_DAO().getallrecords();
                if(allbrandsubcategories!= null  && allbrandsubcategories.size()>0)
                {
                    for(Brandsubcategory_TO bsc : allbrandsubcategories)
                    {
                        jcb_bsid.addItem(bsc);
                    }
                }
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jcb_bid = new javax.swing.JComboBox();
        jcb_scid = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jcb_bsid = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Select Brand ID :-");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("select Subcategory ID:-");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jcb_bid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcb_bid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcb_scid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcb_scid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("select Brand Subcategory:-");

        jcb_bsid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcb_bsid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addComponent(jcb_bid, 0, 205, Short.MAX_VALUE)
                    .addComponent(jcb_scid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_bsid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jcb_bid))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jcb_scid))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jcb_bsid))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean allvalid;
    private String brandid,message;
    private int subcategoryid;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Brandinfo_TO r = (Brandinfo_TO) jcb_bid.getSelectedItem();
        brandid = r.getBrandid();
        Subcategoryinfo_TO s = (Subcategoryinfo_TO) jcb_scid.getSelectedItem();
        subcategoryid=s.getSubcategoryid();
        allvalid=true;
        if(jcb_bid.getSelectedIndex()<0||jcb_bsid.getSelectedIndex()<0||jcb_scid.getSelectedIndex()<0)
        {
            message = "one or more values are not selected";
            allvalid=false;
        }
        if(allvalid)
        {
            Brandsubcategory_TO record = new Brandsubcategory_TO();
            record.setBrandid(brandid);
            record.setSubcategoryid(subcategoryid);
            Brandsubcategory_DAO action =new Brandsubcategory_DAO();
            switch(o)
            {
                case 1:
                    if(action.insertrecord(record))
            {
                message = "Brand successfully added in system";
            }
            else
            {
                message = "Insertion failure ::"+action.getErrormessage();
            }
                    break;
                case 2:
                    Brandsubcategory_TO q = (Brandsubcategory_TO) jcb_bsid.getSelectedItem();
                    record.setSrno(q.getSrno());
                    if(action.updaterecord(record))
            {
                message = "Brand successfully updaded in system";
            }
            else
            {
                message = "updation failure ::"+action.getErrormessage();
            }
                    break;
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox jcb_bid;
    private javax.swing.JComboBox jcb_bsid;
    private javax.swing.JComboBox jcb_scid;
    // End of variables declaration//GEN-END:variables
}
