/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brandoperations_ui;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.Brandinfo_DAO;
import model.dao.Brandsubcategory_DAO;
import model.to.Brandinfo_TO;
import model.to.Brandsubcategory_TO;
import ui.Mainscreen;
import utility.Checks;

/**
 *
 * @author LAKSHAY DUTTA
 */
public class View_brandsubcategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form View_brandsubcategory
     */
        private List<Brandsubcategory_TO> allcategories;
    private int srow;
    private JPopupMenu popup;
    public View_brandsubcategory() {
        initComponents();
        setSize(800,500);
        setVisible(true);
        bindTableDetails();
        srow = -1;
        popup = new JPopupMenu();
        JMenuItem deleteitem = new JMenuItem("Delete Record");
        deleteitem.setFont(new Font("Arial", Font.BOLD, 25));
        JMenuItem edititem = new JMenuItem("Edit Record");
        edititem.setFont(new Font("Arial", Font.BOLD, 25));
        popup.add(deleteitem);
        popup.add(edititem);
        deleteitem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
        edititem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                editRecord();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("View All Subcategories...");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        if(evt.getButton()==MouseEvent.BUTTON3)
        {
            int point = tbl.rowAtPoint(evt.getPoint());
            tbl.getSelectionModel().setSelectionInterval(point, point);
            popup.show(tbl,evt.getX(),evt.getY());
            srow = tbl.getSelectedRow();
            popup.show(tbl, evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_tblMouseClicked
    public void bindTableDetails() {
        allcategories = new Brandsubcategory_DAO().getallrecords();
        String[] col_names = {"Sr no.", "Brand ID","Brand name"};
        Object[][] records = null;
        if (allcategories != null && allcategories.size() > 0) {
            records = new Object[allcategories.size()][col_names.length];
            int i = 0;
            for (Brandsubcategory_TO ct : allcategories) {
                records[i] = new Object[]{ct.getSrno(), ct.getBrandid(),ct.getBrandname()};
                i++;
            }
        } else {
            records = new Object[1][col_names.length];
            records[0] = new Object[]{"No Records", "No Records","No Records"};
        }
        DefaultTableModel dtm = new DefaultTableModel(records, col_names) {
            @Override
        public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl.setModel(dtm);
    }
    
    
    private void deleteRecord() {
        if (srow != -1 && allcategories != null && srow < allcategories.size()) {
            int result = JOptionPane.showConfirmDialog(this, "Are You Sure To Removed This Reccord?", "Message From System", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                Brandsubcategory_TO ci = allcategories.get(srow);
                Brandsubcategory_DAO action = new Brandsubcategory_DAO();
                String message = "";
                if (action.deleterecord(ci.getSrno())) {
                    message = "Record is Removed From Database";
                    bindTableDetails();
                } else {
                    message = action.getErrormessage();
                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
        srow = -1;
    }

    private void editRecord() {
        if (srow != -1 && allcategories != null && srow < allcategories.size()) {
            Checks.openInternalFrame(Mainscreen.getDeskpane(), new Input_brandsubcategory(2));
            dispose();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
