/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import User_operations.Add_new_user;
import User_operations.update_user;
import billoperations_ui.Create_bill_id;
import java.util.List;
import javax.swing.JOptionPane;
import model.dao.Logininfo_DAO;
import model.to.Logininfo_TO;
import partydetails_ui.Insert_party;
import partydetails_ui.View_party;
import utility.Checks;

/**
 *
 * @author LAKSHAY DUTTA
 */
public class Login_ckeck extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login_ckeck
     */
    private static String upass,uname;
     boolean allvalid;
     String message = "";
     private int operation;
     private static List<Logininfo_TO> users;
    public Login_ckeck(int operation) {
        initComponents();
        this.operation=operation;
         users = new Logininfo_DAO().getallrecords();
        jcb_uname.removeAllItems();
        jcb_uname.addItem("Select A User");
        if(users != null && users.size() >0)
        {
            for(Logininfo_TO li : users)
            {
                jcb_uname.addItem(li);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcb_uname = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_pass = new javax.swing.JPasswordField();
        jRadioButton1 = new javax.swing.JRadioButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter your password");

        jcb_uname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcb_uname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select Username");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("okay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Do not show this option for this session");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_pass))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_uname, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(tf_pass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       allvalid=true;
        if(!Checks.isempty(tf_pass.getText()))
       {
           upass=tf_pass.getText();
       }else{
            message = " please enter your password";
            allvalid=false;
       }
        if(jcb_uname.getSelectedIndex() < 0)
        {
            message = " please select a user";
            allvalid=false;
        }
        if(allvalid)
        {
            Logininfo_TO li = (Logininfo_TO) jcb_uname.getSelectedItem();
            uname=li.getUname();
           // System.out.println(uname);
            for(Logininfo_TO l : users)
            {
                if(l.getUname().equals(uname))
                {
                  //  System.out.println("name match");
                    //System.out.println(li.getUname());
                   // System.out.println(uname);
                    if(l.getUpass().equals(upass))
                    {
                     //   System.out.println("password match");
                        message="Log in successfull";
                        switch(operation)
                        {
                            case 1:
                               // System.out.println(uname);
                                Checks.openInternalFrame(getDesktopPane(),new Insert_party(1,uname));
                                break;
                            case 2:
                                Checks.openInternalFrame(getDesktopPane(), new View_party(uname));
                                break;
                            case 3:
                                Checks.openInternalFrame(getDesktopPane(), new Create_bill_id(1, uname) );
                                break;
                            /*case 4:
                                Checks.openInternalFrame(getDesktopPane(), new Create_a_bill(uname));
                                break;*/
                            case 5:
                                Checks.openInternalFrame(getDesktopPane(), new Add_new_user(1));
                                break;
                            case 6:
                                Checks.openInternalFrame(getDesktopPane(), new update_user(uname));
                        }
                    }else{
                      //  System.out.println(li.getUpass());
                   // System.out.println(upass);
                        message="Could not Log you in";
                    }
                }   
            }
        }
        JOptionPane.showMessageDialog(getDesktopPane(), message);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JComboBox jcb_uname;
    private javax.swing.JPasswordField tf_pass;
    // End of variables declaration//GEN-END:variables
}
